# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'listen-ios' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for listen-ios
  pod 'SocketRocket'
  pod 'MD5Digest'

  target 'listen-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'listen-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
